theme: catppuccin-macchiato
foreground: "#cad3f5"
background: "#494d64"
black: "#494d64"
gray: "#6e738d"
bright_gray: "#a5adcb"
white: "#eff1f5"
red: "#ed8796"
bright_red: "#ee99a0"
green: "#a6da95"
bright_green: "#a6da95"
primary_color_subdued: "#b7bdf8"
primary_color: "#c6a0f6"
status_color: "#eed49f"
