theme: catppuccin-macchiato
background: "#494d64"
foreground: "#cad3f5"
black: "#494d64"
bright_black: "#494d64"
gray: "#6e738d"
bright_gray: "#a5adcb"
white: "#eff1f5"
primary_color: "#c6a0f6"
primary_color_subdued: "#b7bdf8"
red: "#ed8796"
bright_red: "#ee99a0"
green: "#a6da95"
bright_green: "#a6da95"
status_color: "#eed49f"
